# Generated by Django 4.1.6 on 2023-07-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='año',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='descripcion_detallada',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='dimensiones',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='estado',
            field=models.CharField(choices=[('Optimo', 'Óptimo'), ('Buen estado', 'Buen estado'), ('Por restaurar', 'Por restaurar'), ('Sin especificar', 'Sin especificar')], default='Optimo', max_length=200),
        ),
        migrations.AddField(
            model_name='productos',
            name='informacion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='peso',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
