# Generated by Django 4.1.6 on 2023-07-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productos_año_productos_descripcion_detallada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
