# Generated by Django 4.1.6 on 2023-07-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_productos_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='descripcion_detallada',
        ),
    ]
